apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-release-proxy.fullname" . }}
  labels:
    {{- include "github-release-proxy.labels" . | nindent 4 }}
data:
  appsettings.Production.json: {{ dict "settings" .Values.settings | toJson | b64enc | quote }}